name: Add git tag
on:
  pull_request:
    types: [closed]
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  release-candidate:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'release')
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: checkout
        uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - name: Check CHANGELOG
        run: |
          if [[ $(grep "${{ steps.release.outputs.version }}" CHANGELOG.md) == "" ]]; then
            echo "VERSION MISMATCH"
            exit 1
          fi
      - name: Add tag
        if: github.event.pull_request.merged == true
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo $PR_TITLE | grep -e "release.*" || exit 1
          git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git tag $(echo $PR_TITLE | sed -E 's/.* (v[0-9\-\.]*)/\1/g')
          git tag -l
          git push origin --tags